/**
 * Include this file if you want to compile the library as a single unit
 */
#include "Arguments.cpp"
#include "Hashing.cpp"
#include "Log.cpp"
#include "Parsing.cpp"
#include "Str.cpp"
#include "StringBuilder.cpp"
#include "FileSystem/FileSystem.cpp"
#include "Memory/Base.cpp"
#include "Memory/Arena.cpp"
#include "Memory/Pool.cpp"
#include "Memory/Sentry.cpp"
#include "Thread/ThreadContext.cpp"
#include "Time/Time.cpp"
#include "Types.cpp"